name: Auto Merge aliyun

on:
  push:
    branches:
      # 不使用该工作流了 因为我们没有 aliyun 分支。也没有对应的 GH_TOKEN_AUTO_MERGE 令牌。
      - main-notuse
  workflow_dispatch: # 手动触发

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_AUTO_MERGE }}

      - name: Merge main into aliyun
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout aliyun
          git merge main --no-ff -m "Auto merge main into aliyun"
          git push origin aliyun
